import type { FundInput, FundProfile, TypeIdentification } from '../types/fundAnalysis';

const SAMPLE_PROFILES: FundProfile[] = [
  {
    code: '018173',
    name: '华泰柏瑞中证电力ETF联接C',
    company: '华泰柏瑞基金',
    manager: '尤家妤',
    inceptionDate: '2023-04-14',
    scale: '2.83亿元',
    type: '指数型',
    riskLevel: '中高风险',
    investmentScope: 'A股',
    coreDirection: '电力公用事业',
    currentStyle: '防御、高股息、低波动',
    latestNav: 1.3545,
    accumulatedNav: 1.3545,
    return1m: 12.51,
    return3m: 14.88,
    return6m: 20.89,
    return1y: 27.7,
    return3y: 30.72,
    maxDrawdown: -12.8,
    volatility: 15.4,
    sharpeRatio: 0.86,
    holdings: [
      { name: '长江电力', weight: 9.8, industry: '水电' },
      { name: '中国核电', weight: 7.2, industry: '核电' },
      { name: '华能国际', weight: 6.6, industry: '火电' },
      { name: '国投电力', weight: 5.9, industry: '水电' },
      { name: '三峡能源', weight: 5.1, industry: '新能源电力' },
    ],
    industryAllocation: [
      { name: '水电', weight: 31 },
      { name: '火电', weight: 24 },
      { name: '核电', weight: 16 },
      { name: '新能源电力', weight: 18 },
      { name: '现金及其他', weight: 11 },
    ],
    stockPosition: 88,
    bondPosition: 0,
    cashPosition: 12,
    trackingIndex: '中证全指电力公用事业指数',
    trackingError: 1.57,
    feeRate: 0.6,
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '008254',
    name: '华宝致远混合(QDII)C',
    company: '华宝基金',
    manager: '周晶、杨洋',
    inceptionDate: '2019-11-27',
    scale: '3.94亿元',
    type: 'QDII',
    riskLevel: '高风险',
    investmentScope: '美股',
    coreDirection: '海外科技成长',
    currentStyle: 'AI 算力、半导体、集中成长',
    latestNav: 2.0141,
    accumulatedNav: 2.0141,
    return1m: 23.15,
    return3m: 36.63,
    return6m: 52.32,
    return1y: 100.53,
    return3y: 157.2,
    maxDrawdown: -34.5,
    volatility: 29.6,
    sharpeRatio: 1.18,
    holdings: [
      { name: '英伟达', weight: 7.79, industry: 'AI芯片' },
      { name: 'Lumen', weight: 7.07, industry: '光通信' },
      { name: '闪迪', weight: 5.47, industry: '存储芯片' },
      { name: '美光科技', weight: 4.53, industry: '存储芯片' },
      { name: '博通', weight: 4.15, industry: '半导体' },
    ],
    industryAllocation: [
      { name: '半导体', weight: 32 },
      { name: '光通信', weight: 21 },
      { name: '互联网', weight: 14 },
      { name: '云计算', weight: 10 },
      { name: '现金及其他', weight: 23 },
    ],
    stockPosition: 84,
    bondPosition: 0,
    cashPosition: 16,
    overseasMarket: '美国科技股',
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '270042',
    name: '广发纳斯达克100ETF联接(QDII)A',
    company: '广发基金',
    manager: '刘杰',
    inceptionDate: '2012-08-15',
    scale: '56.21亿元',
    type: 'QDII',
    riskLevel: '中高风险',
    investmentScope: '美股',
    coreDirection: '纳斯达克100宽基指数',
    currentStyle: '美股大型科技、指数跟踪',
    latestNav: 5.218,
    accumulatedNav: 5.218,
    return1m: 8.4,
    return3m: 17.2,
    return6m: 26.5,
    return1y: 43.8,
    return3y: 88.7,
    maxDrawdown: -28.2,
    volatility: 24.8,
    sharpeRatio: 0.92,
    holdings: [
      { name: '微软', weight: 8.3, industry: '软件' },
      { name: '英伟达', weight: 7.8, industry: 'AI芯片' },
      { name: '苹果', weight: 7.4, industry: '消费电子' },
      { name: '亚马逊', weight: 5.1, industry: '互联网' },
      { name: 'Meta', weight: 4.6, industry: '互联网' },
    ],
    industryAllocation: [
      { name: '软件', weight: 25 },
      { name: '半导体', weight: 22 },
      { name: '互联网', weight: 18 },
      { name: '消费电子', weight: 13 },
      { name: '现金及其他', weight: 22 },
    ],
    stockPosition: 90,
    bondPosition: 0,
    cashPosition: 10,
    trackingIndex: '纳斯达克100指数',
    trackingError: 0.85,
    feeRate: 0.8,
    overseasMarket: '美国成长股',
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '016186',
    name: '广发中证全指电力ETF联接C',
    company: '广发基金',
    manager: '陆志明',
    inceptionDate: '2022-07-19',
    scale: '7.62亿元',
    type: '指数型',
    riskLevel: '中风险',
    investmentScope: 'A股',
    coreDirection: '电力公用事业',
    currentStyle: '防御、红利、行业指数',
    latestNav: 1.263,
    accumulatedNav: 1.263,
    return1m: 10.16,
    return3m: 13.4,
    return6m: 18.9,
    return1y: 25.1,
    return3y: 26.3,
    maxDrawdown: -10.9,
    volatility: 13.1,
    sharpeRatio: 0.91,
    holdings: [
      { name: '长江电力', weight: 10.2, industry: '水电' },
      { name: '国电电力', weight: 6.9, industry: '火电' },
      { name: '中国广核', weight: 5.8, industry: '核电' },
      { name: '川投能源', weight: 5.4, industry: '水电' },
      { name: '华电国际', weight: 4.6, industry: '火电' },
    ],
    industryAllocation: [
      { name: '水电', weight: 34 },
      { name: '火电', weight: 23 },
      { name: '核电', weight: 13 },
      { name: '新能源电力', weight: 17 },
      { name: '现金及其他', weight: 13 },
    ],
    stockPosition: 86,
    bondPosition: 0,
    cashPosition: 14,
    trackingIndex: '中证全指电力公用事业指数',
    trackingError: 1.1,
    feeRate: 0.55,
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '012922',
    name: '易方达全球成长精选混合(QDII)人民币C',
    company: '易方达基金',
    manager: '郑希',
    inceptionDate: '2021-08-24',
    scale: '15.32亿元',
    type: 'QDII',
    riskLevel: '高风险',
    investmentScope: '全球市场',
    coreDirection: '全球成长精选',
    currentStyle: '全球科技、成长风格',
    latestNav: 0.8856,
    accumulatedNav: 0.8856,
    return1m: 6.8,
    return3m: 12.5,
    return6m: 18.3,
    return1y: 28.6,
    return3y: -11.4,
    maxDrawdown: -42.5,
    volatility: 26.8,
    sharpeRatio: 0.52,
    holdings: [
      { name: '英伟达', weight: 6.2, industry: 'AI芯片' },
      { name: '台积电', weight: 5.8, industry: '半导体' },
      { name: '微软', weight: 4.9, industry: '软件' },
      { name: '比亚迪', weight: 4.3, industry: '新能源车' },
      { name: '三星电子', weight: 3.7, industry: '消费电子' },
    ],
    industryAllocation: [
      { name: '半导体', weight: 28 },
      { name: '软件', weight: 18 },
      { name: '新能源车', weight: 15 },
      { name: '消费电子', weight: 12 },
      { name: '现金及其他', weight: 27 },
    ],
    stockPosition: 78,
    bondPosition: 0,
    cashPosition: 22,
    overseasMarket: '全球成长股',
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '018036',
    name: '长城全球新能源车股票发起式(QDII)C',
    company: '长城基金',
    manager: '曲少杰',
    inceptionDate: '2022-01-27',
    scale: '4.28亿元',
    type: 'QDII',
    riskLevel: '高风险',
    investmentScope: '全球市场',
    coreDirection: '全球新能源车',
    currentStyle: '新能源车产业链、全球配置',
    latestNav: 0.9124,
    accumulatedNav: 0.9124,
    return1m: 5.2,
    return3m: 9.8,
    return6m: 14.6,
    return1y: 22.3,
    maxDrawdown: -38.2,
    volatility: 28.4,
    sharpeRatio: 0.45,
    holdings: [
      { name: '特斯拉', weight: 7.5, industry: '新能源车' },
      { name: '比亚迪', weight: 6.8, industry: '新能源车' },
      { name: '宁德时代', weight: 5.9, industry: '锂电池' },
      { name: '蔚来', weight: 4.2, industry: '新能源车' },
      { name: 'LG化学', weight: 3.6, industry: '锂电池' },
    ],
    industryAllocation: [
      { name: '新能源车', weight: 38 },
      { name: '锂电池', weight: 22 },
      { name: '智能驾驶', weight: 12 },
      { name: '充电基建', weight: 8 },
      { name: '现金及其他', weight: 20 },
    ],
    stockPosition: 82,
    bondPosition: 0,
    cashPosition: 18,
    overseasMarket: '全球新能源车产业链',
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '110011',
    name: '易方达优质精选混合(QDII)',
    company: '易方达基金',
    manager: '张坤',
    inceptionDate: '2008-06-19',
    scale: '289.56亿元',
    type: 'QDII',
    riskLevel: '中高风险',
    investmentScope: 'A股+港股',
    coreDirection: '优质精选、价值成长',
    currentStyle: '大盘成长、白酒+互联网',
    latestNav: 4.3835,
    accumulatedNav: 5.1235,
    return1m: 3.2,
    return3m: 8.6,
    return6m: 12.4,
    return1y: 18.5,
    return3y: -25.6,
    maxDrawdown: -48.2,
    volatility: 22.5,
    sharpeRatio: 0.38,
    holdings: [
      { name: '贵州茅台', weight: 9.8, industry: '白酒' },
      { name: '腾讯控股', weight: 8.5, industry: '互联网' },
      { name: '泸州老窖', weight: 6.2, industry: '白酒' },
      { name: '洋河股份', weight: 5.1, industry: '白酒' },
      { name: '美团-W', weight: 4.8, industry: '互联网' },
    ],
    industryAllocation: [
      { name: '白酒', weight: 32 },
      { name: '互联网', weight: 24 },
      { name: '医药', weight: 12 },
      { name: '消费', weight: 10 },
      { name: '现金及其他', weight: 22 },
    ],
    stockPosition: 85,
    bondPosition: 0,
    cashPosition: 15,
    overseasMarket: 'A股+港股',
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '161725',
    name: '招商中证白酒指数(LOF)A',
    company: '招商基金',
    manager: '侯昊',
    inceptionDate: '2015-05-27',
    scale: '320.45亿元',
    type: '指数型',
    riskLevel: '中高风险',
    investmentScope: 'A股',
    coreDirection: '白酒行业',
    currentStyle: '行业集中、白酒龙头',
    latestNav: 1.2456,
    accumulatedNav: 2.8567,
    return1m: 2.8,
    return3m: 6.5,
    return6m: 10.2,
    return1y: 15.8,
    return3y: -18.5,
    maxDrawdown: -42.8,
    volatility: 25.6,
    sharpeRatio: 0.35,
    holdings: [
      { name: '贵州茅台', weight: 15.2, industry: '白酒' },
      { name: '五粮液', weight: 14.8, industry: '白酒' },
      { name: '泸州老窖', weight: 10.5, industry: '白酒' },
      { name: '山西汾酒', weight: 8.2, industry: '白酒' },
      { name: '洋河股份', weight: 7.6, industry: '白酒' },
    ],
    industryAllocation: [
      { name: '白酒', weight: 88 },
      { name: '现金', weight: 12 },
    ],
    stockPosition: 95,
    bondPosition: 0,
    cashPosition: 5,
    trackingIndex: '中证白酒指数',
    trackingError: 0.65,
    feeRate: 1.0,
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '005827',
    name: '易方达蓝筹精选混合',
    company: '易方达基金',
    manager: '张坤',
    inceptionDate: '2018-09-05',
    scale: '462.78亿元',
    type: '偏股混合型',
    riskLevel: '中高风险',
    investmentScope: 'A股+港股',
    coreDirection: '蓝筹精选',
    currentStyle: '大盘蓝筹、白酒+互联网',
    latestNav: 1.5234,
    accumulatedNav: 1.8234,
    return1m: 3.5,
    return3m: 9.2,
    return6m: 13.8,
    return1y: 20.5,
    return3y: -22.3,
    maxDrawdown: -45.6,
    volatility: 21.8,
    sharpeRatio: 0.42,
    holdings: [
      { name: '贵州茅台', weight: 9.5, industry: '白酒' },
      { name: '腾讯控股', weight: 8.2, industry: '互联网' },
      { name: '泸州老窖', weight: 6.8, industry: '白酒' },
      { name: '五粮液', weight: 5.5, industry: '白酒' },
      { name: '美团-W', weight: 4.9, industry: '互联网' },
    ],
    industryAllocation: [
      { name: '白酒', weight: 30 },
      { name: '互联网', weight: 22 },
      { name: '医药', weight: 14 },
      { name: '消费', weight: 12 },
      { name: '现金及其他', weight: 22 },
    ],
    stockPosition: 88,
    bondPosition: 0,
    cashPosition: 12,
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
  {
    code: '012414',
    name: '华夏纳斯达克100ETF联接(QDII)A',
    company: '华夏基金',
    manager: '赵宗庭',
    inceptionDate: '2020-10-22',
    scale: '28.95亿元',
    type: 'QDII',
    riskLevel: '中高风险',
    investmentScope: '美股',
    coreDirection: '纳斯达克100宽基指数',
    currentStyle: '美股科技、指数跟踪',
    latestNav: 1.8562,
    accumulatedNav: 1.8562,
    return1m: 7.8,
    return3m: 16.5,
    return6m: 25.2,
    return1y: 42.5,
    return3y: 85.3,
    maxDrawdown: -27.5,
    volatility: 23.8,
    sharpeRatio: 0.95,
    holdings: [
      { name: '苹果', weight: 8.8, industry: '消费电子' },
      { name: '英伟达', weight: 7.5, industry: 'AI芯片' },
      { name: '微软', weight: 7.2, industry: '软件' },
      { name: '亚马逊', weight: 5.3, industry: '互联网' },
      { name: 'Meta', weight: 4.8, industry: '互联网' },
    ],
    industryAllocation: [
      { name: '软件', weight: 26 },
      { name: '半导体', weight: 20 },
      { name: '互联网', weight: 18 },
      { name: '消费电子', weight: 14 },
      { name: '现金及其他', weight: 22 },
    ],
    stockPosition: 92,
    bondPosition: 0,
    cashPosition: 8,
    trackingIndex: '纳斯达克100指数',
    trackingError: 0.78,
    feeRate: 0.8,
    overseasMarket: '美国科技股',
    source: 'mock 数据层，参考公开基金披露字段',
    dataDate: '2026-06-01',
  },
];

function inferCompany(name: string): string {
  const companies: [string, string][] = [
    ['华泰柏瑞', '华泰柏瑞基金'],
    ['华宝', '华宝基金'],
    ['广发', '广发基金'],
    ['易方达', '易方达基金'],
    ['长城', '长城基金'],
    ['南方', '南方基金'],
    ['华夏', '华夏基金'],
    ['嘉实', '嘉实基金'],
    ['博时', '博时基金'],
    ['招商', '招商基金'],
    ['富国', '富国基金'],
    ['汇添富', '汇添富基金'],
    ['中欧', '中欧基金'],
    ['景顺长城', '景顺长城基金'],
    ['工银瑞信', '工银瑞信基金'],
    ['鹏华', '鹏华基金'],
    ['天弘', '天弘基金'],
    ['交银', '交银施罗德基金'],
    ['兴证全球', '兴证全球基金'],
    ['中银', '中银基金'],
    ['建信', '建信基金'],
    ['银华', '银华基金'],
    ['国泰', '国泰基金'],
    ['大成', '大成基金'],
    ['诺安', '诺安基金'],
  ];
  for (const [keyword, company] of companies) {
    if (name.includes(keyword)) return company;
  }
  return '基金公司信息待更新';
}

function inferDirection(name: string, type: string): string {
  const keywords: [string, string][] = [
    ['电力', '电力公用事业'],
    ['新能源', '新能源产业链'],
    ['纳斯达克', '纳斯达克100宽基指数'],
    ['科技', '科技创新'],
    ['医药', '医药健康'],
    ['消费', '大消费'],
    ['半导体', '半导体芯片'],
    ['军工', '国防军工'],
    ['白酒', '白酒消费'],
    ['光伏', '光伏产业链'],
    ['锂电', '锂电池产业链'],
    ['AI', '人工智能'],
    ['互联网', '互联网科技'],
    ['全球成长', '全球成长精选'],
    ['全球新能源', '全球新能源车'],
    ['红利', '高股息红利'],
  ];
  for (const [keyword, direction] of keywords) {
    if (name.includes(keyword)) return direction;
  }
  if (type === 'QDII') return '海外资产配置';
  if (type === '债券型') return '固定收益';
  if (type === '货币型') return '现金管理';
  return '均衡配置';
}

function fallbackProfile(input: FundInput, identification: TypeIdentification): FundProfile {
  const isBond = identification.fundType === '债券型';
  const isMoney = identification.fundType === '货币型';
  const baseReturn = isMoney ? 1.8 : isBond ? 4.2 : identification.fundType === 'QDII' ? 18 : 9;

  return {
    code: input.code,
    name: input.name,
    company: inferCompany(input.name),
    manager: '基金经理信息待更新',
    inceptionDate: '2020-01-15',
    scale: '18.60亿元',
    type: identification.fundType,
    riskLevel: isMoney ? '低风险' : isBond ? '中低风险' : '中高风险',
    investmentScope: identification.investmentScope,
    coreDirection: inferDirection(input.name, identification.fundType),
    currentStyle: isBond ? '稳健久期、信用精选' : isMoney ? '高流动性、现金管理' : identification.fundType === 'QDII' ? '全球配置、成长风格' : '均衡成长、分散配置',
    latestNav: isMoney ? 1 : 1.368,
    accumulatedNav: isMoney ? 1 : 1.728,
    return1m: baseReturn / 8,
    return3m: baseReturn / 3,
    return6m: baseReturn / 1.8,
    return1y: baseReturn,
    return3y: baseReturn * 2.2,
    maxDrawdown: isMoney ? -0.1 : isBond ? -3.8 : -18.6,
    volatility: isMoney ? 0.4 : isBond ? 4.6 : 18.2,
    sharpeRatio: isMoney ? 0.72 : isBond ? 0.76 : 0.68,
    holdings: [
      { name: isBond ? '国债' : '核心资产A', weight: 8.2, industry: isBond ? '利率债' : '科技' },
      { name: isBond ? '政策性金融债' : '核心资产B', weight: 7.4, industry: isBond ? '金融债' : '消费' },
      { name: isBond ? '高等级信用债' : '核心资产C', weight: 6.1, industry: isBond ? '信用债' : '医药' },
    ],
    industryAllocation: isBond
      ? [
          { name: '利率债', weight: 42 },
          { name: '金融债', weight: 28 },
          { name: '信用债', weight: 18 },
          { name: '现金', weight: 12 },
        ]
      : [
          { name: '科技', weight: 26 },
          { name: '消费', weight: 21 },
          { name: '医药', weight: 15 },
          { name: '高端制造', weight: 14 },
          { name: '现金及其他', weight: 24 },
        ],
    stockPosition: isBond || isMoney ? 0 : 82,
    bondPosition: isMoney ? 55 : isBond ? 86 : 0,
    cashPosition: isMoney ? 45 : isBond ? 14 : 18,
    duration: isBond ? '中短久期' : undefined,
    creditBondRatio: isBond ? 18 : undefined,
    convertibleBondRatio: isBond ? 6 : undefined,
    sevenDayAnnualized: isMoney ? 1.82 : undefined,
    tenThousandIncome: isMoney ? 0.49 : undefined,
    source: 'mock 数据层，待接入真实基金 API',
    dataDate: '2026-06-01',
  };
}

export async function fetchFundBasicInfo(
  input: FundInput,
  identification: TypeIdentification
): Promise<FundProfile> {
  // TODO: Replace with a real fund basic info API when provider credentials and schema are available.
  const matched = SAMPLE_PROFILES.find((fund) => fund.code === input.code);
  return matched ? { ...matched, name: input.name || matched.name } : fallbackProfile(input, identification);
}

export async function fetchFundNavHistory(): Promise<number[]> {
  // TODO: Replace with real NAV history data.
  return [0.6, 1.1, 2.7, 3.4, 4.9, 6.2, 5.8, 7.1];
}

export async function fetchFundHoldings(profile: FundProfile): Promise<FundProfile['holdings']> {
  // TODO: Replace with real quarterly holdings.
  return profile.holdings;
}

export async function fetchMarketData(): Promise<{ rateTone: string; equityTone: string; fxTone: string }> {
  // TODO: Replace with macro, rate, valuation, and currency data feeds.
  return {
    rateTone: '利率环境整体平稳，但海外利率仍会影响成长资产估值',
    equityTone: '权益市场结构分化，资金偏好确定性和景气度较高的方向',
    fxTone: '汇率波动会影响 QDII 净值折算和短期表现',
  };
}

export async function getMockFundData(
  input: FundInput,
  identification: TypeIdentification
): Promise<FundProfile> {
  const profile = await fetchFundBasicInfo(input, identification);
  const holdings = await fetchFundHoldings(profile);
  return { ...profile, holdings };
}
